apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  name: svc-ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
      app: container-ftps
  ports:
    - name: ftp-1
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftp-2
      protocol: TCP
      port: 21000
      targetPort: 21000
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: deploy-ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-ftps
  template:
    metadata:
      labels:
        app: container-ftps
    spec:
      containers:
        - name: ftps-cont
          image: my_ftps
          ports:
            - containerPort: 21
            - containerPort: 21000
          imagePullPolicy: Never
