apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  name: svc-phpmyadmin
spec:
  loadBalancerIP: 192.168.99.100
  type: LoadBalancer
  selector:
      app: container-phpmyadmin
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: php-port
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: deploy-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-phpmyadmin
  template:
    metadata:
      labels:
        app: container-phpmyadmin
    spec:
      containers:
        - name: phpmyadmin-cont
          image: my_php
          ports:
            - containerPort: 5000
          imagePullPolicy: Never
