apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
  selector:
    app : wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: deploy-wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wp
        name: wordpress-cont
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wordpress
